default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') { '' } %>

development:
  <<: *default
  database: survey_system_development'

staging:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE') { '' } %> 

test:
  <<: *default
  database: survey_system_test

production:
  <<: *default
  database: survey_system_production
  username: <%= ENV["PRODUCTION_DATABASE_USER"] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  socket: "/cloudsql/<%= ENV['CLOUD_SQL_CONNECTION_NAME'] %>"
