source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 7.0.3'
gem 'puma', '~> 5.0'
gem 'config'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'jwt'
gem 'kaminari'
gem 'rack-cors'
gem 'dotenv-rails'
gem 'pg'

group :development, :test do
  gem 'annotate'
  gem 'committee-rails'
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rails-erd'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-daemon', require: false # @see https://github.com/fohte/rubocop-daemon
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'rubocop-performance'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'letter_opener_web'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
